spring:
    h2.console:
        enabled: true
        path: /h2
    thymeleaf:
        cache: false
    datasource:
        url: jdbc:h2:~/test
        username: sa
        password: 
        driverClassName: org.h2.Driver
    jpa.database-platform: org.hibernate.dialect.H2Dialect

jwt.token.secret: ENC(F2APOMS5ZI5A+eFR5PFATxnI/pWHlg0I)

#security.user:
#    name: admin
#    password: password
    

spring.social:
    facebook:
        app-id: ENC(0d5NcLs9dEsdwlrnAuOlbSJOXeS6CLET)
        appId: ENC(0d5NcLs9dEsdwlrnAuOlbSJOXeS6CLET)
        app-secret: ENC(H9mD5PoKvGgoR3vKA4bmINFkNMW7c09LaMnQEzwLQNSaPooWCLiRPX8z6mhwwZ7h)
        appSecret: ENC(H9mD5PoKvGgoR3vKA4bmINFkNMW7c09LaMnQEzwLQNSaPooWCLiRPX8z6mhwwZ7h)
    linkedin:
        app-id: ENC(7DVUYUKmj+WzJ8ztkFJUwavA/3u/Sc9i)
        app-secret: ENC(Ae+GrVddwruQaNy+44vz2vwtV1Q+ZoRAY6URAoeRkcg=)
    youtube:
        app-id: ytCoop
        api-key: ENC(8Vr5ig9rIqenTLTXC+iFvodw3uFXIXB6K3ZMujg0Zbk1fkc52n7QJ8HFO71RS67N)

logging.level.org.springframework.security: DEBUG


ytcoop:
    feedbackurl: http://goo.gl/forms/omzPb3TcNJ