spring:
    h2.console:
        enabled: true
        path: /h2
    thymeleaf:
        cache: false


#security.user:
#    name: admin
#    password: password
    
    
spring.social:
    facebook:
        app-id: ENC(0d5NcLs9dEsdwlrnAuOlbSJOXeS6CLET)
        app-secret: ENC(H9mD5PoKvGgoR3vKA4bmINFkNMW7c09LaMnQEzwLQNSaPooWCLiRPX8z6mhwwZ7h)
    youtube:
        app-id: ytCoop
        api-key: ENC(8Vr5ig9rIqenTLTXC+iFvodw3uFXIXB6K3ZMujg0Zbk1fkc52n7QJ8HFO71RS67N)

logging.level.org.springframework.security: INFO